server.port=${PORT:8080}
spring.application.name=crypto-query-service

# URL del consumer-service
consumer.service.url=http://localhost:8081/internal/crypto

# Ruta del Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Conexion a Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.data.redis.url=${SPRING_REDIS_URL:redis://localhost:6379}

# Tiempo de vida del cache: 5 minutos en ms
cache.ttl.seconds=300
