server.port=8081
spring.application.name=crypto-consumer-service

# URL base de CoinGecko API v3
coingecko.api.base-url=https://api.coingecko.com/api/v3

# Monedas a traer
coingecko.api.coins-limit=15

# Habilitar el pool de hilos para @Scheduled
spring.task.scheduling.pool.size=2
