server.port=8082
spring.application.name=crypto-management-service

# URL del consumer-service para validar que el id existe antes de agregarlo
consumer.service.url=http://localhost:8081/internal/crypto
